apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: info-pages-prd
nameSuffix: -prd

commonLabels:
  app: info-pages-prd

patches:
  - path: deployment_image.yml
    target:
      kind: Deployment