apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: info-pages-prd
nameSuffix: -prd

commonLabels:
  app: info-pages-prd

patchesStrategicMerge:
  - deployment_image.yml
