# add branches to trigger builds here
trigger:
  - dev
  - master

pool:
  name: default

variables:
  isProd: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/dev')]

jobs:
  - job: ImageDoesNotExist
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: '! docker manifest inspect pgc-docker.artifactory.umn.edu/pgc-info-pages:$IMAGE_TAG'
        env:
          IMAGE_TAG: $(Build.SourceVersion)
  - job: BuildAndPushImage
    dependsOn:
      - ImageDoesNotExist
    workspace:
      clean: all
    steps:
      - template: az-pipeline-templates/build.yml
  - job: DeployTestClusterDev
    dependsOn:
      - ImageDoesNotExist
      - BuildAndPushImage
    condition: and(or(succeeded('BuildAndPushImage'), failed('ImageDoesNotExist')), eq(variables.isDev, 'true'))
    workspace:
      clean: all
    steps:
      - template: az-pipeline-templates/deploy.yml
        parameters:
          env: dev
          overlay: dev
          namespace: info-pages-dev
          k8sSvcConnection: "AKS k8s-tst cluster - info-pages-dev"
  - job: DeployTestClusterPrd
    dependsOn:
      - ImageDoesNotExist
      - BuildAndPushImage
    condition: and(or(succeeded('BuildAndPushImage'), failed('ImageDoesNotExist')), eq(variables.isDev, 'false'))
    workspace:
      clean: all
    steps:
      - template: az-pipeline-templates/deploy.yml
        parameters:
          env: prd
          overlay: prd
          namespace: info-pages-prd
          k8sSvcConnection: "AKS k8s-tst cluster - info-pages-prd"
