---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: placeholder
  name: info-pages
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: frontend
        image: placeholder
        resources:
          requests:
            cpu: 50m
            memory: "100Mi"
          limits:
            cpu: 200m
            memory: "100Mi"
        ports:
        - containerPort: 8080
